sequenceDiagram
    actor Alice
    actor Bob

    %% import ./test/a.mmd
    
    Alice->>Bob: Hi Bob
    Bob->>Alice: Hi Alice

    %% import ./test/b.mmd

    Alice->>Bob: Hi Bob
    Bob->>Alice: Hi Alice